# These settings are used as defaults
[Config]
BaseConfig = "/etc/cme/timesnap/default.backup.config.toml"
Description = "An example service"
Environment = "development"
Name = "Some Service"

[Config.DB]
Driver = "mysql"
Host = "localhost"
Name = "db-name"
Password = "PAssW04D"
Port = 3306
Sock = "/run/mysqld/mysqld.sock"
User = "mysql"

[Config.DB.Backup]
Driver = "mysql"
Host = "localhost"
Name = "db-name"
Password = "PAssW04D"
Port = 3306
Sock = "/run/mysqld/mysqld.sock"
User = "mysql"

[Config.DB.Timesnap]
BinaryDump = true
Databases = []
Incremental = true
KeepDays = 30
Profile = "Backup"
SQLDump = false
TargetDir = "/backup/www-backup/db"

[Config.FS.Timesnap]
Excludes = ["/var/www/logs", "/var/www/htdocs"]
KeepDays = 30
Minspace = 95
SourceDir = ["/root", "/var/www"]
TargetHost = "localhost"
TargetDir = "/backup/www-backup/fs"

[Config.Log]
File = "/var/log/timesnap.backup.log"
