# Edit this config to suit your environment
[Config]
BaseConfig = "/etc/cme/timesnap/default.backup.toml"
Description = "An example service"
Environment = "development"
Name = "Some Service"

[Config.DB]
Driver = "mysql"
Host = "localhost"
Name = "db-name"
Password = "PAssW04D"
Port = 3306
Sock = "/run/mysqld/mysqld.sock"
User = "mysql"

[Config.DB.Backup]
Driver = "mysql"
Host = "localhost"
Name = "db-name"
Password = "PAssW04D"
Port = 3306
Sock = "/run/mysqld/mysqld.sock"
User = "mysql"

[Config.DB.Timesnap]
BinaryDump = true
Databases = ["db1", "somedb2"]
Incremental = true
KeepDays = 30
DBProfile = "Backup"
SQLDump = false
TargetDir = "/backup/www-backup/db"

[Config.FS.Timesnap]
Excludes = ["/var/www/logs", "/var/www/htdocs"]
KeepDays = 30
Minspace = 95
SourceDir = ["/root", "/var/www"]
TargetHost = "ninja.flipkick.media"
TargetDir = "/backup/www-backup/fs"

[Config.Log]
File = "/var/log/timesnap.backup.log"
